# -*- coding: utf-8 -*-
"""Similitud semántica csv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hPfw4TMTMwlnJTHgB7KiKg8DtB23cscC
"""

# Establecer un vinculo con Drive

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Leer archivo CSV y cargar en dataframe
df = pd.read_csv("/content/drive/MyDrive/Comparación de algoritmos de extracción de palabras clave/scopus2.csv", encoding="utf-8")
df.head()

# Eliminar filas que no tienen datos en la columna "nombre_de_columna"
#df.dropna(subset=["Author Keywords"], inplace=True)

#df.head()

# Obtener las tres primeras palabras clave separadas por punto y coma de las columnas "Columna1" y "Columna2"
keywords1 = df["Author Keywords"].str.split(';', expand=True).iloc[:, :3]
keywords2 = df["GPT"].str.split(';', expand=True).iloc[:, :3]

# Unir las palabras clave de cada fila en una cadena de texto
keywords1 = df["Author Keywords"].str.split(';', expand=True).apply(lambda row: ' '.join(row.dropna().values.astype(str)), axis=1)
keywords2 = df["GPT"].str.split(';', expand=True).apply(lambda row: ' '.join(row.dropna().values.astype(str)), axis=1)

# Crear el objeto vectorizador tf-idf y ajustarlo con las palabras clave unidas
vectorizer = TfidfVectorizer()
vectorizer.fit(keywords1.append(keywords2))

# Transformar las palabras clave de cada columna en vectores tf-idf
tfidf_vectors1 = vectorizer.transform(keywords1).toarray()
tfidf_vectors2 = vectorizer.transform(keywords2).toarray()

# Calcular la similitud del coseno entre los vectores tf-idf de cada fila
similarity_scores = cosine_similarity(tfidf_vectors1, tfidf_vectors2)

# Agregar los resultados de similitud como una nueva columna al dataframe original
df['similarity_GPT'] = similarity_scores.diagonal()

df

df.to_csv("/content/drive/MyDrive/Comparación de algoritmos de extracción de palabras clave/scopus2.csv", encoding="utf-8")